# CHUK MCP Time Server Configuration
host:
  name: "chuk-time-mcp-server"
  log_level: "INFO"

server:
  type: "stdio"  # Options: stdio, websocket

mcp_servers:
  time_server:
    enabled: true
    location: "."
    tools:
      enabled: true
      module: "chuk_mcp_artifact_server.tools"