# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# Set environment variables to prevent .pyc files and enable unbuffered output
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# Copy required files
COPY pyproject.toml ./
COPY README.md ./
COPY manifest.in ./
COPY src ./src
COPY tests ./tests
COPY uv.lock ./
COPY uvx.toml ./

# Install build dependencies
RUN pip install --upgrade pip

# Install the package
RUN pip install .

# Expose the default port if any (not specified but can be added if needed)
# EXPOSE 8000

# Command to run the MCP server
ENTRYPOINT ["chuk-mcp-time-server"]
